// Build step: read plaintext src/puzzles.js and emit src/puzzles.enc.js.
// Ladderle's start/end/len/par (and n/date) are PUBLIC — they're on screen the
// moment the day loads — so each day ships {n, date, start, end, len, par} in
// the clear plus an `enc` blob holding ONLY `path` (the verified optimal ladder,
// used for hints — the one thing worth hiding from view-source). The app imports
// ONLY the encoded file and decode()s in-memory at play time. Runs after
// test/validate.mjs in `npm run build` (the full structural gate lives there;
// the checks here guard the encoding itself and hard-fail on date gaps,
// duplicate dates, and round-trip mismatches even when run standalone).
//
// Fixture overrides (infra self-testing only — the real build never sets these):
// LADDERLE_PUZZLES = abs path to a throwaway puzzles module,
// LADDERLE_ENC_OUT = abs path for the emitted file (keeps fixtures out of src/).
import { writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { encode, decode } from './src/cipher.js';

function fail(msg) { console.error('ENCODE FAIL:', msg); process.exit(1); }

const puzzlesUrl = process.env.LADDERLE_PUZZLES
  ? pathToFileURL(process.env.LADDERLE_PUZZLES).href
  : new URL('./src/puzzles.js', import.meta.url).href;
let PUZZLES;
try { ({ PUZZLES } = await import(puzzlesUrl)); }
catch (err) { fail(`cannot load puzzles module (${err.message}) — content not written yet?`); }

if (!Array.isArray(PUZZLES) || PUZZLES.length === 0) fail('src/puzzles.js exports no puzzles');

// 1. no duplicate dates, and dates contiguous (a gap breaks BY_DATE nav — viral-game pillar 1)
const sorted = [...PUZZLES].sort((a, b) => (a.date < b.date ? -1 : 1));
const seenDates = new Set();
for (const p of sorted) {
  if (seenDates.has(p.date)) fail(`DUPLICATE DATE ${p.date}`);
  seenDates.add(p.date);
}
for (let i = 1; i < sorted.length; i++) {
  const prev = new Date(sorted[i - 1].date + 'T00:00:00Z');
  const next = new Date(sorted[i].date + 'T00:00:00Z');
  if (next - prev !== 86400000) fail(`DATE GAP between ${sorted[i - 1].date} and ${sorted[i].date}`);
}

// 2. numbering contiguous from 1, matching date order
sorted.forEach((p, i) => { if (p.n !== i + 1) fail(`n out of sequence at ${p.date}: n=${p.n}, expected ${i + 1}`); });

// 3. every puzzle: encodable shape (validate.mjs is the full gate; this is the floor)
for (const p of PUZZLES) {
  if (typeof p.start !== 'string' || typeof p.end !== 'string') fail(`#${p.n} missing start/end`);
  if (!Number.isInteger(p.len) || !Number.isInteger(p.par)) fail(`#${p.n} missing len/par`);
  if (!Array.isArray(p.path) || p.path.length < 2 || !p.path.every((w) => typeof w === 'string')) {
    fail(`#${p.n} path must be an array of >= 2 words`);
  }
  if (p.path[0] !== p.start || p.path[p.path.length - 1] !== p.end) fail(`#${p.n} path endpoints != start/end`);
}

// 4. encode: ONLY `path` goes through the cipher; everything else is public UI state
const enc = PUZZLES.map((p) => ({
  n: p.n, date: p.date, start: p.start, end: p.end, len: p.len, par: p.par,
  enc: encode(p.path, p.date),
}));

const out =
  '// AUTO-GENERATED by encode-puzzles.mjs — do not edit. {n,date,start,end,len,par}\n' +
  '// are public (on-screen anyway); `enc` is the optimal path, XOR+base64 obfuscated\n' +
  '// per day (see cipher.js). Edit src/puzzles.js and rebuild.\n' +
  'export const PUZZLES = ' + JSON.stringify(enc) + ';\n';

// 5. leak check: no INTERMEDIATE rung (path[1..-2] — the secret part; start/end are
// public) may sit in the clear. Scanned PER ENTRY, not globally: a hidden rung of one
// day may legitimately be another day's public start/end, but it can never appear in
// its own day's entry outside the blob. Two needle forms per rung: quoted (`"CORD"` —
// a direct leak, e.g. `path` accidentally kept on the clear object) and once-escaped
// (`\"CORD\"` — leaked INSIDE a string value, e.g. if the cipher ever degrades to a
// no-op). Neither '"' nor '\' is in the base64 alphabet, so a match can only be a
// real leak — this stays honest even if cipher.js is broken.
const leaks = [];
for (const [i, p] of PUZZLES.entries()) {
  const entryText = JSON.stringify(enc[i]);
  if (!/^[A-Za-z0-9+/]+=*$/.test(enc[i].enc)) fail(`#${p.n} enc blob is not clean base64`);
  // inner scan: peel the base64 layer and needle-scan the raw bytes too — catches a
  // cipher degraded to btoa-without-XOR (blob is clean base64, round-trips fine, but
  // the plaintext sits one trivial decode away). With a live keystream the inner
  // bytes are noise; an exact `"CORD"` collision is ~2^-48 per position — negligible.
  const inner = Buffer.from(enc[i].enc, 'base64').toString('latin1');
  for (const rung of p.path.slice(1, -1)) {
    const quoted = JSON.stringify(rung);
    const escapedOnce = JSON.stringify(quoted).slice(1, -1);
    if (entryText.includes(quoted) || entryText.includes(escapedOnce)) leaks.push(`#${p.n} rung ${rung}`);
    if (inner.includes(quoted)) leaks.push(`#${p.n} rung ${rung} (readable through the base64 layer — cipher XOR dead?)`);
  }
}
if (leaks.length) fail('LEAK in encoded output: ' + leaks.slice(0, 6).join(', '));

// 6. positive check: every blob round-trips byte-for-byte back to the source path
for (const e of enc) {
  const src = PUZZLES.find((p) => p.n === e.n);
  let got;
  try { got = decode(e.enc, e.date); } catch (err) { fail(`ROUND-TRIP FAIL on #${e.n}: ${err.message}`); }
  if (JSON.stringify(got) !== JSON.stringify(src.path)) fail(`ROUND-TRIP FAIL on #${e.n}`);
}

// only write once every check has passed — a failing run must never leave output behind
const outPath = process.env.LADDERLE_ENC_OUT ?? new URL('./src/puzzles.enc.js', import.meta.url);
writeFileSync(outPath, out);
console.log(`encoded ${enc.length} puzzles (${sorted[0].date} -> ${sorted[sorted.length - 1].date}) -> src/puzzles.enc.js (path-only blob; no leak; all round-trip OK)`);
