import { useState, useEffect, useMemo, useCallback, useRef } from 'preact/hooks';
import { decode } from './cipher.js';
import { Reveal } from './reveal.jsx';

/* ═══════════════════════════════════════════════════════════════════════
 * Puzzle + dictionary source.
 *
 * REAL data: src/puzzles.enc.js (generated by encode-puzzles.mjs from the
 * content agent's src/puzzles.js — {n,date,start,end,len,par} in the clear,
 * `path` inside the per-day `enc` blob) plus a dictionary module.
 *
 */
import { PUZZLES } from './puzzles.enc.js';
import { WORDS as RAW_WORDS } from './words.js';
import { EPOCH, addDays, numberForDate, indexForDate } from './schedule.js';

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const WD = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

// LOOPS FOREVER now (src/schedule.js): a puzzle's `date` is just its authoring id /
// cipher key; the calendar day decides which puzzle plays via the stride walk, so it
// never sticks on #last (it used to stop on the final dated puzzle, 2026-11-16).
const POOL = PUZZLES.slice().sort((a, b) => a.n - b.n);
const N = POOL.length;
const puzzleForDate = (d) => POOL[indexForDate(d, N)] || POOL[0];
const CAL_WINDOW = 56;
const calDates = (today) => { const span = Math.min(CAL_WINDOW, numberForDate(today)); return Array.from({ length: span }, (_, i) => addDays(today, -(span - 1 - i))).filter((d) => d >= EPOCH); };

const up = (s) => String(s).toUpperCase();

/* ---------- dictionary: per-length word sets ---------- */
const BUCKETS = new Map(); // len -> Set(word)
function bucket(len) {
  let b = BUCKETS.get(len);
  if (!b) { b = new Set(); BUCKETS.set(len, b); }
  return b;
}
{
  // Accept any reasonable dictionary shape: array, Set, whitespace string, or
  // an object keyed by length whose values are arrays/Sets/packed strings
  // (the real words.js ships { 3: Set, 4: Set, 5: Set } of lowercase words).
  const expand = (v) =>
    Array.isArray(v) ? v
      : v instanceof Set ? [...v]
        : typeof v === 'string' ? v.split(/\s+/)
          : [];
  let flat = [];
  if (RAW_WORDS instanceof Set || Array.isArray(RAW_WORDS) || typeof RAW_WORDS === 'string') flat = expand(RAW_WORDS);
  else if (RAW_WORDS && typeof RAW_WORDS === 'object') flat = Object.values(RAW_WORDS).flatMap(expand);
  for (const w of flat) {
    const u = up(w).trim();
    if (/^[A-Z]+$/.test(u)) bucket(u.length).add(u);
  }
  // Every day's endpoints are public and must always validate.
  for (const p of PUZZLES) { bucket(p.len).add(up(p.start)); bucket(p.len).add(up(p.end)); }
}

/* ---------- word-graph: neighbors, BFS distance-to-END, next step ---------- */
const PATTERNS = new Map(); // len -> Map('C·LD' -> [words])
const DISTS = new Map();    // `${len}:${end}` -> Map(word -> dist)

function patternMap(len) {
  let m = PATTERNS.get(len);
  if (!m) {
    m = new Map();
    for (const w of bucket(len)) {
      for (let i = 0; i < len; i++) {
        const k = w.slice(0, i) + '·' + w.slice(i + 1);
        const arr = m.get(k);
        if (arr) arr.push(w); else m.set(k, [w]);
      }
    }
    PATTERNS.set(len, m);
  }
  return m;
}
function neighbors(w) {
  const m = patternMap(w.length);
  const out = [];
  for (let i = 0; i < w.length; i++) {
    const list = m.get(w.slice(0, i) + '·' + w.slice(i + 1));
    if (list) for (const x of list) if (x !== w) out.push(x);
  }
  return out;
}
function addWords(words, len) {
  const b = bucket(len);
  let added = false;
  for (const w of words) if (w.length === len && !b.has(w)) { b.add(w); added = true; }
  if (added) {
    PATTERNS.delete(len);
    for (const k of [...DISTS.keys()]) if (k.startsWith(len + ':')) DISTS.delete(k);
  }
}
function distMap(end) {
  const key = end.length + ':' + end;
  let d = DISTS.get(key);
  if (!d) {
    d = new Map([[end, 0]]);
    const q = [end];
    for (let qi = 0; qi < q.length; qi++) {
      const w = q[qi];
      const dw = d.get(w);
      for (const nb of neighbors(w)) if (!d.has(nb)) { d.set(nb, dw + 1); q.push(nb); }
    }
    DISTS.set(key, d);
  }
  return d;
}
// Next optimal rung from `cur`: prefer the curated path (SPEC: optimal rungs
// must be common words), else any BFS-shortest neighbor.
function nextStep(cur, end, path) {
  if (path) {
    const i = path.indexOf(cur);
    if (i >= 0 && i < path.length - 1) return path[i + 1];
  }
  const d = distMap(end);
  const dc = d.get(cur);
  if (dc == null || dc === 0) return null;
  const cands = neighbors(cur).filter((nb) => d.get(nb) === dc - 1);
  if (!cands.length) return null;
  if (path) for (const c of cands) if (path.includes(c)) return c;
  return cands.sort()[0];
}
// One square per rung: 🟩 iff that move strictly decreased BFS distance to END
// (a step along SOME shortest route from where you stood) — else 🟨 detour.
function squaresFor(start, rungs, end) {
  const d = distMap(end);
  let prev = start;
  const out = [];
  for (const w of rungs) {
    const dp = d.get(prev), dw = d.get(w);
    out.push(dp != null && dw != null && dw === dp - 1 ? '🟩' : '🟨');
    prev = w;
  }
  return out;
}

// -1 = identical, -2 = more than one letter differs, else the single diff index
function diffIdx(a, b) {
  let idx = -1;
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) { if (idx >= 0) return -2; idx = i; }
  }
  return idx;
}
function diffCount(a, b) {
  let n = 0;
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) n++;
  return n;
}

// The hidden optimal path, decoded lazily and cached per puzzle number.
// Accepts every wrapping the pipeline might hand us: a plaintext array (dev
// fixture), enc = encode(pathArray), enc = encode({path}), or a cipher STRING
// (possibly double-wrapped — puzzles.js pre-obfuscates `path` and the encoder
// wraps whatever it's given).
function unwrapPath(x, date, depth) {
  if (depth > 3 || x == null) return null;
  if (Array.isArray(x)) return x.map(up);
  if (typeof x === 'object' && Array.isArray(x.path)) return x.path.map(up);
  if (typeof x === 'string') {
    try { return unwrapPath(decode(x, date), date, depth + 1); }
    catch { return null; }
  }
  return null;
}
const PATH_CACHE = new Map();
function puzzlePath(p) {
  if (PATH_CACHE.has(p.n)) return PATH_CACHE.get(p.n);
  let path = unwrapPath(p.enc, p.date, 0) || unwrapPath(p.path, p.date, 0);
  if (!(path && path.length >= 2 && path.every((w) => typeof w === 'string' && w.length === p.len))) path = null;
  PATH_CACHE.set(p.n, path);
  return path;
}

/* ---------- date helpers (sibling-identical) ---------- */
function localDateStr(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const da = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${da}`;
}
function parseDate(s) { const [y, m, d] = s.split('-').map(Number); return new Date(y, m - 1, d); }
function shortDate(s) { const [, m, d] = s.split('-').map(Number); return `${WD[parseDate(s).getDay()]} ${MONTHS[m - 1]} ${d}`; }
const clampDay = (d, t) => (d < EPOCH ? EPOCH : d > t ? t : d);
function msToMidnight() {
  const n = new Date();
  const nx = new Date(n.getFullYear(), n.getMonth(), n.getDate() + 1, 0, 0, 0, 0);
  return nx - n;
}
function fmtCountdown(ms) {
  const s = Math.max(0, Math.floor(ms / 1000));
  const h = String(Math.floor(s / 3600)).padStart(2, '0');
  const m = String(Math.floor((s % 3600) / 60)).padStart(2, '0');
  const ss = String(s % 60).padStart(2, '0');
  return `${h}:${m}:${ss}`;
}
function deepLinkDate() {
  try {
    const raw = new URLSearchParams(location.search).get('d');
    if (!raw) return null;
    if (/^\d{4}-\d{2}-\d{2}$/.test(raw) && raw >= EPOCH) return raw;
    const n = parseInt(raw, 10);
    if (Number.isFinite(n) && n >= 1) return addDays(EPOCH, n - 1);
  } catch { /* ignore */ }
  return null;
}

/* ---------- stats + per-day play state (localStorage, keyed by DATE) ---------- */
// Ladderle has no losing — `wins` counts PAR matches, `dist` buckets moves-over-par
// (0..4+), `streak` = consecutive par days. Same blob shape as the siblings.
function loadStats() {
  try {
    const s = JSON.parse(localStorage.getItem('ladderle-stats') || '{}');
    return {
      played: s.played || 0, wins: s.wins || 0, streak: s.streak || 0,
      maxStreak: s.maxStreak || 0, dist: s.dist || [0, 0, 0, 0, 0], done: s.done || [],
    };
  } catch { return { played: 0, wins: 0, streak: 0, maxStreak: 0, dist: [0, 0, 0, 0, 0], done: [] }; }
}
function recordResult(key, isPar, over) {
  const s = loadStats();
  if (s.done.includes(key)) return s;
  s.done.push(key); s.played += 1;
  s.dist[Math.max(0, Math.min(4, over))] += 1;
  if (isPar) { s.wins += 1; s.streak += 1; s.maxStreak = Math.max(s.maxStreak, s.streak); }
  else { s.streak = 0; }
  try { localStorage.setItem('ladderle-stats', JSON.stringify(s)); } catch { /* ignore */ }
  return s;
}
function playState(key) {
  try {
    const s = JSON.parse(localStorage.getItem(`ladderle-${key}`) || 'null');
    return s && s.status === 'won' ? 'won' : null;
  } catch { return null; }
}

/* ---------- share ---------- */
function buildShare({ number, start, end, moves, par, hints, sq, url }) {
  const h = hints > 0 ? ` · 💡${hints}` : '';
  return `🪜 Ladderle #${number} — ${start}→${end} in ${moves} (par ${par})${h}\n${sq.join('')}\n${url}`;
}

/* ---------- a single rung row ---------- */
function Rung({ word, prev, label, kind, matchWith, onLetter }) {
  const chg = prev ? diffIdx(prev, word) : -1;
  return (
    <div class={`rung ${kind}`}>
      <span class="rlab">{label}</span>
      <div class="tiles">
        {word.split('').map((ch, j) => {
          let cls = 'tile';
          if (j === chg) cls += ' chg';
          if (matchWith && matchWith[j] === ch) cls += ' hit';
          return onLetter ? (
            <button
              type="button" class={cls + ' t-btn'} key={j}
              aria-label={`Change letter ${j + 1} (${ch})`}
              onPointerDown={(e) => e.preventDefault()}
              onClick={() => onLetter(j)}
            >{ch}</button>
          ) : (
            <span class={cls} key={j}>{ch}</span>
          );
        })}
      </div>
    </div>
  );
}

/* ==================================================================== */
/*  Single-day game (remounts on date switch via key={number})          */
/* ==================================================================== */
function Game({ puzzle, dayKey, number, isToday }) {
  const storeKey = `ladderle-${dayKey}`;
  const start = up(puzzle.start);
  const end = up(puzzle.end);
  const len = puzzle.len || start.length;
  const par = puzzle.par;

  const initial = useMemo(() => {
    try {
      const s = JSON.parse(localStorage.getItem(storeKey) || 'null');
      if (s && Array.isArray(s.rungs)) {
        const rungs = s.rungs.map(up);
        // Structural sanity: an unbroken one-letter chain from START. A save
        // from older/foreign content (dev→real swap) falls back to fresh.
        let ok = true, prev = start;
        for (const w of rungs) {
          if (typeof w !== 'string' || w.length !== len || diffIdx(prev, w) < 0) { ok = false; break; }
          prev = w;
        }
        if (ok) {
          let status = s.status === 'won' ? 'won' : 'playing';
          if (status !== 'won' && rungs.length && rungs[rungs.length - 1] === end) status = 'won'; // heal
          return { rungs, status, hints: s.hints | 0 };
        }
      }
    } catch { /* ignore */ }
    return { rungs: [], status: 'playing', hints: 0 };
  }, [storeKey, start, end, len]);

  const [rungs, setRungs] = useState(initial.rungs);
  const [status, setStatus] = useState(initial.status);
  const [hints, setHints] = useState(initial.hints);
  const [entry, setEntry] = useState('');
  const [sel, setSel] = useState({ s: 0, e: 0 });
  const [focused, setFocused] = useState(false);
  const [msg, setMsg] = useState(null);          // {text, kind:'err'|'hint'|'ok'}
  const [shaking, setShaking] = useState(false);
  const [resetArmed, setResetArmed] = useState(false);
  const [stats, setStats] = useState(loadStats);
  const [countdown, setCountdown] = useState(msToMidnight());
  const [toast, setToast] = useState('');

  const inputRef = useRef(null);
  const scrollRef = useRef(null);
  const timers = useRef([]);
  const hinted = useRef(new Map()); // word -> hinted next (charge once per position)
  const freshWin = useRef(false);   // confetti only on a live win, not a reload

  const done = status === 'won';
  const cur = rungs.length ? rungs[rungs.length - 1] : start;
  const moves = rungs.length;
  const isPar = done && moves === par;

  const t = useCallback((fn, ms) => { timers.current.push(setTimeout(fn, ms)); }, []);
  useEffect(() => () => { timers.current.forEach(clearTimeout); timers.current = []; }, []);

  // persist
  useEffect(() => {
    try { localStorage.setItem(storeKey, JSON.stringify({ rungs, status, hints })); }
    catch { /* ignore */ }
  }, [storeKey, rungs, status, hints]);

  // a healed save finished the day but the crash beat recordResult — record now
  useEffect(() => {
    if (initial.status === 'won' && !loadStats().done.includes(dayKey)) {
      setStats(recordResult(dayKey, initial.rungs.length === par, initial.rungs.length - par));
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // countdown ticker once finished (today only)
  useEffect(() => {
    if (!done || !isToday) return;
    const id = setInterval(() => setCountdown(msToMidnight()), 1000);
    return () => clearInterval(id);
  }, [done, isToday]);

  // keep the active zone (current word → ghost → END) parked above the dock;
  // result screen starts at its top
  useEffect(() => {
    const el = scrollRef.current;
    if (!el) return;
    el.scrollTop = done ? 0 : el.scrollHeight;
  }, [moves, done]);
  useEffect(() => {
    const vv = window.visualViewport;
    if (!vv) return;
    const on = () => {
      const el = scrollRef.current;
      if (el && status === 'playing') el.scrollTop = el.scrollHeight;
    };
    vv.addEventListener('resize', on);
    return () => vv.removeEventListener('resize', on);
  }, [status]);

  /* --- messaging (fixed-height status line; auto-reverts to the counter) --- */
  const msgTimer = useRef(null);
  const flash = useCallback((text, kind) => {
    setMsg({ text, kind });
    if (msgTimer.current) clearTimeout(msgTimer.current);
    if (kind !== 'hint') msgTimer.current = setTimeout(() => setMsg(null), 2400);
  }, []);
  const fail = useCallback((text) => {
    flash(text, 'err');
    setShaking(true);
    setTimeout(() => setShaking(false), 340);
  }, [flash]);

  /* --- the hidden input: native editing drives everything --- */
  const syncSel = useCallback(() => {
    const el = inputRef.current;
    if (!el) return;
    setSel({ s: el.selectionStart ?? 0, e: el.selectionEnd ?? 0 });
  }, []);
  const syncFromInput = useCallback(() => {
    const el = inputRef.current;
    if (!el) return;
    const v = up(el.value).replace(/[^A-Z]/g, '').slice(0, len);
    if (v !== el.value) {
      const at = Math.min(el.selectionStart ?? v.length, v.length);
      el.value = v;
      try { el.setSelectionRange(at, at); } catch { /* ignore */ }
    }
    setEntry(v);
    syncSel();
  }, [len, syncSel]);
  useEffect(() => {
    const on = () => { if (document.activeElement === inputRef.current) syncSel(); };
    document.addEventListener('selectionchange', on);
    return () => document.removeEventListener('selectionchange', on);
  }, [syncSel]);

  const setEntryValue = useCallback((v) => {
    const el = inputRef.current;
    if (el) el.value = v;
    setEntry(v);
  }, []);

  const clearEntry = useCallback(() => { setEntryValue(''); }, [setEntryValue]);

  const popRung = useCallback(() => {
    if (done || !rungs.length) return;
    setRungs((prev) => prev.slice(0, -1));
    setMsg(null);
  }, [done, rungs.length]);

  const undo = useCallback(() => {
    if (done) return;
    if (entry) { clearEntry(); return; }
    popRung();
  }, [done, entry, clearEntry, popRung]);

  const resetTap = useCallback(() => {
    if (done || (!rungs.length && !entry)) return;
    if (!resetArmed) {
      setResetArmed(true);
      t(() => setResetArmed(false), 2200);
      return;
    }
    setResetArmed(false);
    setRungs([]);
    clearEntry();
    flash('Back to the top', 'ok');
  }, [done, rungs.length, entry, resetArmed, clearEntry, flash, t]);

  const submit = useCallback(() => {
    if (done) return;
    const w = entry;
    if (w.length !== len) { fail(`Need ${len} letters`); return; }
    const di = diffIdx(cur, w);
    if (di === -1) { fail(`That's the word you're on — change one letter`); return; }
    if (di === -2) { fail(`Change exactly one letter — that changes ${diffCount(cur, w)}`); return; }
    if (!bucket(len).has(w)) { fail(`${w} isn't in the word list`); return; }
    const next = [...rungs, w];
    setRungs(next);
    setEntryValue('');
    setMsg(null);
    if (w === end) {
      setStatus('won');
      freshWin.current = true;
      setStats(recordResult(dayKey, next.length === par, next.length - par));
      try { inputRef.current && inputRef.current.blur(); } catch { /* ignore */ }
    }
  }, [done, entry, len, cur, rungs, end, par, dayKey, fail, setEntryValue]);

  const doHint = useCallback(() => {
    if (done) return;
    const path = puzzlePath(puzzle);
    if (path) addWords(path, len); // hinted words must pass validation
    const nx = nextStep(cur, end, path);
    if (!nx) { fail('No route from here — undo a step'); return; }
    if (!hinted.current.has(cur)) {
      hinted.current.set(cur, nx);
      setHints((h) => h + 1);
    }
    setEntryValue(nx);
    const el = inputRef.current;
    if (el) { try { const i = diffIdx(cur, nx); el.setSelectionRange(i, i + 1); } catch { /* ignore */ } }
    syncSel();
    flash(`Hint: ${nx} — press ⏎ to place it`, 'hint');
  }, [done, puzzle, len, cur, end, fail, setEntryValue, syncSel, flash]);

  // Tap a letter box (dock) or a letter of the current rung (ladder): prefill
  // the entry with the current word and select exactly that letter — the next
  // keypress replaces it. Native selection does the heavy lifting.
  const tapBox = useCallback((i) => {
    if (done) return;
    const el = inputRef.current;
    if (!el) return;
    if (!el.value) setEntryValue(cur);
    el.focus({ preventScroll: true });
    const v = el.value;
    const s = Math.min(i, v.length);
    const e = Math.min(i + 1, v.length);
    try { el.setSelectionRange(s, e); } catch { /* ignore */ }
    syncSel();
  }, [done, cur, setEntryValue, syncSel]);
  const tapLadder = useCallback((j) => {
    if (done) return;
    const el = inputRef.current;
    if (!el) return;
    setEntryValue(cur);
    el.focus({ preventScroll: true });
    try { el.setSelectionRange(j, j + 1); } catch { /* ignore */ }
    syncSel();
  }, [done, cur, setEntryValue, syncSel]);

  const onInputKey = useCallback((e) => {
    if (e.key === 'Enter') { e.preventDefault(); submit(); return; }
    if (e.key === 'Backspace' && !e.currentTarget.value && !e.repeat) {
      e.preventDefault();
      popRung();
      return;
    }
    requestAnimationFrame(syncSel);
  }, [submit, popRung, syncSel]);

  // desktop: focus on mount; physical keys route to the input from anywhere
  useEffect(() => {
    if (done) return;
    if (matchMedia('(hover: hover) and (pointer: fine)').matches) {
      try { inputRef.current && inputRef.current.focus({ preventScroll: true }); } catch { /* ignore */ }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  useEffect(() => {
    const onKey = (e) => {
      if (done || e.metaKey || e.ctrlKey || e.altKey) return;
      const el = inputRef.current;
      if (!el || document.activeElement === el) return;
      const tg = e.target;
      if (tg && (tg.tagName === 'INPUT' || tg.tagName === 'TEXTAREA' || tg.tagName === 'BUTTON')) return;
      if (/^[a-zA-Z]$/.test(e.key)) {
        e.preventDefault();
        el.focus({ preventScroll: true });
        el.value = (el.value + e.key).toUpperCase().replace(/[^A-Z]/g, '').slice(0, len);
        syncFromInput();
      } else if (e.key === 'Backspace') {
        e.preventDefault();
        el.focus({ preventScroll: true });
        if (el.value) { el.value = el.value.slice(0, -1); syncFromInput(); }
        else if (!e.repeat) popRung();
      } else if (e.key === 'Enter') {
        e.preventDefault();
        submit();
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [done, len, submit, popRung, syncFromInput]);

  /* --- share --- */
  const shareData = useMemo(() => {
    if (!done) return null;
    const path = puzzlePath(puzzle);
    if (path) addWords(path, len);
    return squaresFor(start, rungs, end);
  }, [done, puzzle, start, rungs, end, len]);

  const doShare = useCallback(async () => {
    const url = isToday ? 'https://ladderle.sebland.com' : `https://ladderle.sebland.com/?d=${number}`;
    const text = buildShare({ number, start, end, moves, par, hints, sq: shareData || [], url });
    try { await navigator.clipboard.writeText(text); setToast('Copied results'); }
    catch {
      try { if (navigator.share) { await navigator.share({ text }); return; } } catch { /* ignore */ }
      setToast('Copy failed');
    }
    setTimeout(() => setToast(''), 1700);
  }, [isToday, number, start, end, moves, par, hints, shareData]);

  const pd = (e) => e.preventDefault(); // keep the keyboard up when tapping buttons

  const parPct = stats.played ? Math.round((stats.wins / stats.played) * 100) : 0;
  const canUndo = !done && (rungs.length > 0 || entry.length > 0);
  const canReset = !done && (rungs.length > 0 || entry.length > 0);
  const statusLine = msg
    ? msg.text
    : `MOVES ${moves} · PAR ${par}${hints ? ` · 💡${hints}` : ''}`;

  return (
    <>
      {done && (
        <div class="scroll" ref={scrollRef}>
          <section class={`result${isPar ? ' par' : ''}`}>
            <div class="verdict">
              {isPar
                ? 'Right on par — a perfect ladder 🏆'
                : `Laddered in ${moves} — par is ${par} 🎉`}
            </div>
            <Reveal
              start={start} end={end} rungs={rungs} sq={shareData || []}
              isPar={isPar} celebrate={freshWin.current}
              optPath={isPar ? null : puzzlePath(puzzle)}
            />
            <div class="attempt-log" aria-hidden="true">
              <div class="log-row">
                {(shareData || []).map((s, i) => (
                  <span class={`sq ${s === '🟩' ? 'g' : 'y'}`} key={i} />
                ))}
              </div>
              <div class="log-cap">
                {moves} {moves === 1 ? 'move' : 'moves'}{hints ? ` · 💡${hints} hint${hints === 1 ? '' : 's'}` : ''}
              </div>
            </div>
            <button class="share-btn" onClick={doShare}>Share result</button>
            <div class="stats">
              <div class="stat"><b>{stats.played}</b><span>played</span></div>
              <div class="stat"><b>{parPct}%</b><span>par rate</span></div>
              <div class="stat"><b>{stats.streak}</b><span>par streak</span></div>
              <div class="stat"><b>{stats.maxStreak}</b><span>best</span></div>
            </div>
            {isToday
              ? <div class="next">Next Ladderle in <span class="cd">{fmtCountdown(countdown)}</span></div>
              : <div class="next">You're playing a past Ladderle · pick 📅 for more</div>}
          </section>
        </div>
      )}

      {!done && (
        <>
          <div class="scroll" ref={scrollRef}>
            <div class="ladder" style={`--n:${len}`}>
              <Rung
                word={start} label="START" kind={rungs.length === 0 ? 'start active' : 'start'}
                onLetter={rungs.length === 0 ? tapLadder : null}
              />
              {rungs.map((w, i) => (
                <Rung
                  key={i} word={w} prev={i ? rungs[i - 1] : start} label={String(i + 1)}
                  kind={i === rungs.length - 1 ? 'active fresh' : 'mid'}
                  onLetter={i === rungs.length - 1 ? tapLadder : null}
                />
              ))}
              <div class="rung ghost" aria-hidden="true">
                <span class="rlab">{moves + 1}</span>
                <div class="tiles">
                  {(entry || rungs.length > 0)
                    ? Array.from({ length: len }, (_, j) => (
                      <span class={`tile${entry[j] ? ' filled' : ''}`} key={j}>{entry[j] || ''}</span>
                    ))
                    : <span class="ghost-tip">type the next word — or tap a letter above</span>}
                </div>
              </div>
              <div class="gapdots" aria-hidden="true">· · ·</div>
              <Rung word={end} label="END" kind="end" matchWith={cur} />
            </div>
          </div>

          <div class="dock">
            <div
              class={`dock-status${msg ? ' ' + msg.kind : ''}${!msg && moves > par ? ' over' : ''}`}
              role="status" aria-live="polite"
            >{statusLine}</div>
            <form class={`entry${shaking ? ' shake' : ''}`} action="." style={`--n:${len}`} onSubmit={(e) => { e.preventDefault(); submit(); }}>
              {Array.from({ length: len }, (_, i) => {
                let cls = 'ebox';
                if (entry[i]) cls += ' filled';
                if (focused && (sel.s !== sel.e ? i >= sel.s && i < sel.e : i === sel.s)) cls += ' cur';
                return (
                  <button
                    type="button" class={cls} key={i} aria-label={`Letter ${i + 1}`}
                    onPointerDown={pd} onClick={() => tapBox(i)}
                  >{entry[i] || ''}</button>
                );
              })}
              <input
                ref={inputRef} class="ghost-input" type="search" name="ladderle-q"
                enterkeyhint="go" inputMode="text" maxLength={len}
                autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck={false}
                aria-label="Your next rung"
                onInput={syncFromInput}
                onKeyDown={onInputKey}
                onFocus={() => { setFocused(true); requestAnimationFrame(syncSel); }}
                onBlur={() => setFocused(false)}
              />
            </form>
            <div class="dock-btns">
              <button type="button" class={`db${canUndo ? '' : ' off'}`} aria-disabled={!canUndo} onPointerDown={pd} onClick={undo}>↩ Undo</button>
              <button type="button" class={`db db-reset${canReset ? '' : ' off'}`} aria-disabled={!canReset} onPointerDown={pd} onClick={resetTap}>{resetArmed ? 'Sure?' : 'Reset'}</button>
              <button type="button" class="db" onPointerDown={pd} onClick={doHint}>💡 Hint</button>
              <button type="button" class="go" onPointerDown={pd} onClick={submit}>Add rung</button>
            </div>
          </div>
        </>
      )}

      {toast && <div class="toast" role="status" aria-live="polite">{toast}</div>}
    </>
  );
}

/* ==================================================================== */
/*  Shell: header, date nav, help, calendar, footer                     */
/* ==================================================================== */
export function App() {
  const [today, setToday] = useState(() => localDateStr(new Date()));
  const [selDate, setSelDate] = useState(() => {
    const td = localDateStr(new Date());
    return clampDay(deepLinkDate() || td, td);
  });
  const [calOpen, setCalOpen] = useState(false);
  const [helpOpen, setHelpOpen] = useState(false);

  // iOS: dvh ignores the keyboard — lift the dock by the visual-viewport overlap
  useEffect(() => {
    const vv = window.visualViewport;
    if (!vv) return;
    const on = () => {
      const kb = Math.max(0, window.innerHeight - vv.height - vv.offsetTop);
      document.documentElement.style.setProperty('--kb', kb.toFixed(0) + 'px');
    };
    vv.addEventListener('resize', on);
    vv.addEventListener('scroll', on);
    on();
    return () => {
      vv.removeEventListener('resize', on);
      vv.removeEventListener('scroll', on);
      document.documentElement.style.setProperty('--kb', '0px');
    };
  }, []);

  useEffect(() => {
    const id = setInterval(() => {
      const tt = localDateStr(new Date());
      if (tt !== today) { setToday(tt); setSelDate((prev) => (prev === today ? tt : prev)); }
    }, 15000);
    return () => clearInterval(id);
  }, [today]);

  const puzzle = puzzleForDate(selDate);
  const number = numberForDate(selDate);
  const isToday = selDate === today;
  const canPrev = selDate > EPOCH;
  const canNext = selDate < today;

  useEffect(() => {
    try { history.replaceState(null, '', isToday ? location.pathname : `${location.pathname}?d=${number}`); }
    catch { /* ignore */ }
  }, [number, isToday]);

  return (
    <div class="wrap">
      <header class="head">
        <div class="brand">
          <span class="logo" aria-hidden="true">
            <svg viewBox="0 0 32 32" width="20" height="20">
              <rect x="7.5" y="3.5" width="3.4" height="25" rx="1.7" fill="#fbbf24" />
              <rect x="21.1" y="3.5" width="3.4" height="25" rx="1.7" fill="#fbbf24" />
              <rect x="9.5" y="7.6" width="13" height="3" rx="1.5" fill="#38bdf8" />
              <rect x="9.5" y="14.5" width="13" height="3" rx="1.5" fill="#4ade80" />
              <rect x="9.5" y="21.4" width="13" height="3" rx="1.5" fill="#facc15" />
            </svg>
          </span>
          <h1>LADDERLE</h1>
        </div>
        <div class="head-btns">
          <button class="icon-btn" onClick={() => setCalOpen(true)} aria-label="Pick a day">📅</button>
          <button class="icon-btn" onClick={() => setHelpOpen((v) => !v)} aria-label="How to play" aria-expanded={helpOpen}>?</button>
        </div>
      </header>

      <p class="tagline">Climb from START to END one letter at a time — every rung a real word. Match par for a perfect ladder.</p>

      <div class="meta">
        <button class={`nav${canPrev ? '' : ' off'}`} onClick={() => canPrev && setSelDate(addDays(selDate, -1))} aria-disabled={!canPrev} aria-label="Previous day">‹</button>
        <span class="meta-label">#{number} · {shortDate(selDate)}{isToday ? ' · today' : ''}</span>
        <button class={`nav${canNext ? '' : ' off'}`} onClick={() => canNext && setSelDate(addDays(selDate, 1))} aria-disabled={!canNext} aria-label="Next day">›</button>
      </div>

      {helpOpen && (
        <div class="help">
          <p><b>How to play.</b> Build a word ladder from START down to END.</p>
          <ul>
            <li>Each rung changes <b>exactly one letter</b> of the word above it — and must be a <b>real word</b>. COLD → <b>CORD</b> → <b>WORD</b> → …</li>
            <li><b>Type</b> the next word and hit <b>⏎</b> — or <b>tap a letter</b> of the current word to swap just that one.</li>
            <li>Fiddle freely: <b>↩ Undo</b> takes a rung back (so does ⌫ on an empty entry), <b>Reset</b> starts the ladder over. Only your final ladder counts.</li>
            <li><span class="lg">Match par</span> — the fewest moves possible — for a perfect game. You can't beat it.</li>
            <li><b>💡 Hint</b> fills in the next best rung (hints show in your share).</li>
            <li>New ladder at midnight · <b>📅</b> replays past days.</li>
          </ul>
          <button class="text-btn" onClick={() => setHelpOpen(false)}>got it</button>
        </div>
      )}

      <Game key={number} puzzle={puzzle} dayKey={selDate} number={number} isToday={isToday} />

      {calOpen && (
        <div class="cal-overlay" onClick={() => setCalOpen(false)}>
          <div class="cal" onClick={(e) => e.stopPropagation()}>
            <div class="cal-head"><span>Pick a day</span><button class="cal-x" onClick={() => setCalOpen(false)} aria-label="Close">✕</button></div>
            <div class="cal-grid">
              {calDates(today).map((d) => {
                const st = playState(d);
                let cls = 'cal-cell';
                if (d === selDate) cls += ' sel';
                if (st === 'won') cls += ' won';
                const [, mm, dd] = d.split('-').map(Number);
                return (
                  <button class={cls} key={d}
                    onClick={() => { setSelDate(d); setCalOpen(false); }}>
                    <span class="cal-n">#{numberForDate(d)}</span>
                    <span class="cal-d">{MONTHS[mm - 1]} {dd}</span>
                    <span class="cal-s">{st === 'won' ? '✓' : ''}</span>
                  </button>
                );
              })}
            </div>
          </div>
        </div>
      )}

      <footer class="foot">
        <a href="https://sebland.com">sebland</a>
        <span>a new ladder daily · {PUZZLES.length} days</span>
      </footer>
    </div>
  );
}
